- README.md
> Updates doc with auth management commands

- cmd/helpers.go
- cmd/root.go
- go.mod
- go.sum
> Add colors to help and error messages.

- api/client.go
- api/login.go
- cmd/auth/auth_with_provider.go
- cmd/auth/login.go
- cmd/auth/status.go
- cmd/helpers.go
- cmd/root.go
- core/color/color.go
- core/host.go
- core/iostreams/iostreams.go
- go.mod
- go.sum
- utils/browser.go
- utils/string.go
- utils/string_test.go
> Login with Github to Reliably API for the CLI

- cmd/auth/auth_with_provider.go
- cmd/auth/login.go
> Login with Gitlab from CLI

- CHANGELOG.md
- cmd/completion.go
- cmd/root.go
> Add completion command to generate shell completion scripts 

- cmd/doc.go
- cmd/doc/man.go
- cmd/doc/markdown.go
- go.sum
Useful to generate CLI man style pages for the main doc website
Signed-off-by: Sylvain Hellegouarch <sh@defuze.org>
> Add doc command and subcommands

- utils/map.go
> Add gist & license links for Nested Map Lookup function

- .github/stale.yml
> Add stale bot - fixes #27

- CODE_OF_CONDUCT.md
> Add code of conduct - fixes #31

- CHANGELOG.md
- cmd/reliably/root.go
- core/color/color.go
- core/update/udpate.go
- core/update/update_test.go
- go.mod
- go.sum
- utils/terminal.go
> Add version update check when running CLI

- cmd/reliably/help_topic.go
- cmd/reliably/root.go
> Add support for disabling CLI update check/notif with env var

- CHANGELOG.md
- Makefile
- cmd/reliably/discover.go
- cmd/reliably/root.go
- cmd/reliably/worklow.go
- core/workflows/circleci.go
- core/workflows/circleci_test.go
- core/workflows/github.go
- core/workflows/github_test.go
- core/workflows/gitlab.go
- core/workflows/gitlab_test.go
- core/workflows/workflow.go
- core/workflows/workflow_test.go
- go.mod
- go.sum
- utils/condition_test.go
- utils/git.go
- utils/git_test.go
for GitHub, GitLab & CircleCI platforms
> Generate CI/CD workflows

- CHANGELOG.md
- cmd/reliably/auth/auth_with_provider.go
> Increase http time out to API login call - fixes #43

- CHANGELOG.md
- core/discover.go
- core/models.go
- core/output/code_climate_format.go
- core/output/formatter.go
- core/suggestion.go
> Ad suggestion level, to discovery output - fixes #52

- CHANGELOG.md
- cmd/reliably/discover.go
- core/models.go
- utils/array.go
> Add flag --level to filter out suggestions only for level and higher

- core/color/color.go
- core/models.go
> Add colors to suggestions output

- .github/workflows/release.yaml
> Fix tar command ti remove parent directory

- .github/workflows/release.yaml
> Update workflow to use latest version of krew release bot

- CHANGELOG.md
- core/kubernetes/kubernetes.go
> Add K8s api call to list nodes for kubernetes live scan

- core/output/sarif_format.go
> Add suggestion example to sarif report

- cmd/reliably/scan.go
- core/models.go
- core/output/formatter.go
- go.mod
- go.sum
- utils/string.go
- utils/string_test.go
> add formatted tabbed output

- CHANGELOG.md
> added entry for tabbed output format

- cmd/reliably/report/cmd.go
- core/manifest/types.go
- core/metrics/common.go
- core/report/generate.go
- core/report/math.go
- reliably.yaml
* added a map of providers
* added resource string parsing
* added some utility maths functions
> Handle multiple metrics providers

- cmd/reliably/scan/terraform/cmd.go
This pull request resolves #105
> Terraform Scanning - Allow Subdirectory lookups

- cmd/reliably/scan/terraform/cmd.go
- scan/scan.go
- scan/scan_test.go
This pull request resolves #106 
- export ErrNotFound as public var and adjusted message
- adjusted terraform scan output
> Terraform Scan Output Fix

- CHANGELOG.md
- cmd/reliably/scan.go
* updated the changelog
* commented out the code that was being used to wire up the `scan terraform` command
> Unwire scan terraform command

- cmd/reliably/slo/init/cmd.go
- core/report/writer.go
- reliably.yaml
* refactored the questions to set the `Provider` property of dependencies
* a bit of house keeping re: manifest creation
* fixed a typo or 2
fixes #128
> Fix issue 128

- cmd/reliably/slo/init/cmd.go
- cmd/reliably/slo/init/cmd_info.go
- core/cli/question/question.go
- reliably.yaml
* reworked the UX of `reliably slo init`
* removed `scanner` arg from functions in the `question` package
> Fix issue 134

- cmd/reliably/slo/report/cmd.go
- core/kubernetes/const.go
- core/report/generate.go
- core/report/report.go
- core/report/writer.go
- go.mod
- go.sum
This Pull Request updates the SLO report output formats.
__Tabbed:__
__JSON:__
```sh
$ reliably slo report --format json
{
"api_version": "1.0rc",
"timestamp": "2021-04-01T15:50:31.291065Z",
"dependencies": [],
"service_level": {
"target": {
"error_percent": 1,
"latency_ms": 300
},
"actual": {
"error_percent": 0,
"latency_ms": 761
},
"delta": {
"error_percent": -1,
"latency_ms": 461
}
},
"window": {
"from": "2021-03-31T16:50:31.298781+01:00",
"to": "2021-04-01T16:50:31.298781+01:00"
}
}
```
__Simple:__
```
$ reliably slo report --format simple
WARN[0001] You are under your error budget by 1.00 percent. You could tighten your budget, or could decrease the quality of the experience your application provides (e.g by reducing the amount of resources given to your application). 
WARN[0001] The …
```
> SLO Report Output update

- cmd/reliably/history.go
> Fix history write to stdout & stderr

- cmd/reliably/slo/init/cmd.go
- cmd/reliably/slo/report/cmd.go
> fix slo init & report flags short names & desc - fixes #145

- cmd/reliably/slo/init/cmd.go
> Add missing word

- cmd/reliably/slo/init/cmd.go
> Use sanitized string in Google resource ID.

- cmd/reliably/slo/init/cmd.go
> Fix indentation

- cmd/reliably/slo/init/cmd.go
> Removes first question on slo init command - fixes #157

- core/report/writer.go
> Adjust auto the col size, depending on the terminal size at runtime

- core/metrics/aws/aws.go
- core/metrics/gcp/gcp.go
- core/metrics/provider.go
- core/report/generate.go
- core/report/generate_test.go
> Fix availability computing: 100% - error rate

- README.md
Signed-off-by: Sylvain Hellegouarch <sh@defuze.org>
> Make README a bit nicer looking

- CHANGELOG.md
- core/report/writer.go
- core/report/writer_test.go
> fix missing SLO with unknown/no result - fixes #208

- examples/reliably.yaml
Closes #193
Signed-off-by: Sylvain Hellegouarch <sh@defuze.org>
@dmartin35 @xaah could you make sure the example doesn't say anything stupid please ?
> Fix manifest example

- cmd/reliably/slo/init/aws.go
- cmd/reliably/slo/init/cmd.go
- cmd/reliably/slo/init/gcp.go
Move aws/gcp variables into adhoc file
> Remove unused variables.

- CHANGELOG.md
- cmd/reliably/slo/init/aws.go
> add validation for AWS ARN on user prompt during slo init - fixes #223

- cmd/reliably/root.go
- core/color/color.go
- go.mod
> customize survey default answer coloring - fixes #231

- CHANGELOG.md
- core/report/generate.go
- core/report/generate_test.go
- core/report/report.go
- core/report/writer.go
- core/report/writer_test.go
> Expose if SLO is met as part of the SLO result in the report - fixes #237

- CHANGELOG.md
- cmd/reliably/slo/report/cmd.go
- core/report/writer.go
> Fix slo report output to file & combined with format flag - fixes #241

- cmd/reliably/root.go
> Amended update message when a new version is available

- cmd/reliably/root.go
> added  upgrade message for windows platform

- cmd/reliably/slo/init/cmd_info.go
> update the example in the slo init help page

- cmd/reliably/slo/apply/cmd.go
> updated help output for slo apply -f

- CHANGELOG.md
- core/report/writer.go
> New SLO report table format (allowed,  consumed, remaining error budget)

- CHANGELOG.md
- cmd/reliably/root.go
- cmd/reliably/update.go
- core/update/udpate.go
- go.mod
- go.sum
> Add update command for installing latest version of the CLI

- CHANGELOG.md
- core/report/writer.go
> added the type of the sli to the text format report

- CHANGELOG.md
Hi @dmartin35!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/reliablyhq/cli/actions/runs/895285338.
I've updated the changelog in this commit: c6c5f7db48122ab47da9fc32e8303e35b6b0b280.
Merging this PR will create a new tag on main branch that will create/build the release of the CLI.
> Release version v0.16.1

- CHANGELOG.md
- cmd/reliably/slo/report/cmd.go
- core/report/markdown_templates.go
- core/report/writer.go
- core/report/writer_test.go
> added report templates

- CHANGELOG.md
This PR was created in response to a manual trigger by @gtfisher of the release workflow here: https://github.com/reliablyhq/cli/actions/runs/925277885.
I've updated the changelog in this commit: bad61c3b51b2325ce1068a21373fdb999b2c707f.
> Release version v0.17.0

- core/report/markdown_templates.go
- core/report/writer.go
> fix typos in markdown, improve layout in the markdown tables

- CHANGELOG.md
- core/report/writer.go
> fixed the trend output to terminal and added span elements for markdown

- cmd/reliably/alpha/slo/init/cmd.go
> Fix duplicated objective written to manifest file with slo init

- Makefile
- cmd/reliably/root.go
- cmd/reliably/version.go
- cmd/reliably/version_test.go
- utils/git.go
- version/version.go
> Expose git rev short sha for default dev version

- CHANGELOG.md
This PR was created in response to a manual trigger by @dmartin35 of the release workflow here: https://github.com/reliablyhq/cli/actions/runs/949875647.
I've updated the changelog in this commit: 683c02da03b621c96181c8fbb87dbccca094ba9f.
> Release version v0.18.1

- Makefile
> Add make clean command, to remove bin folder & built exec

- CHANGELOG.md
This PR was created in response to a manual trigger by @dmartin35 of the release workflow here: https://github.com/reliablyhq/cli/actions/runs/964735484.
I've updated the changelog in this commit: edfe0dc3f6581ccc2bf13d86ffe44f98c5f60f8e.
> Release version v0.19.0

- CHANGELOG.md
- api/organization.go
- cmd/reliably/auth/login.go
> Save default user org into config upon successful authentication

- CHANGELOG.md
- cmd/reliably/history.go
- cmd/reliably/scan/kubernetes.go
- cmd/reliably/slo/agent/cmd.go
- cmd/reliably/slo/report/cmd.go
- cmd/reliably/slo/sync/cmd.go
> Use config ID & Name from config, not only user's default org

- CHANGELOG.md
This PR was created in response to a manual trigger by @dmartin35 of the release workflow here: https://github.com/reliablyhq/cli/actions/runs/978208433.
I've updated the changelog in this commit: d295f16bb9acf6c423c9a7a75231f0fb26b06f06.
> Release version v0.19.1

- CHANGELOG.md
- cmd/reliably/org/set/cmd.go
> Removes a debug statement (print) for org set command

- CHANGELOG.md
This PR was created in response to a manual trigger by @dmartin35 of the release workflow here: https://github.com/reliablyhq/cli/actions/runs/982052235.
I've updated the changelog in this commit: 13cbf60b0443e28fcbc796a162d093306785adb3.
> Release version v0.19.2

- cmd/reliably/help_topic.go
> Add env ver for reliably org to environment command - fixes #360

- CHANGELOG.md
This PR was created in response to a manual trigger by @dmartin35 of the release workflow here: https://github.com/reliablyhq/cli/actions/runs/986376621.
I've updated the changelog in this commit: 7f92df904f93e9b476cec9a1cec788547a255b31.
> Release version v0.19.3

- CHANGELOG.md
- core/update/update.go
> Fixes release file path not expanded from user home ~

- CHANGELOG.md
- api/organization.go
- cmd/reliably/root.go
- config/const.go
- config/org.go
- config/vars.go
> Sets org info when using RELIABLY_ORG env var - fixes #361

- CHANGELOG.md
This PR was created in response to a manual trigger by @dmartin35 of the release workflow here: https://github.com/reliablyhq/cli/actions/runs/989835053.
I've updated the changelog in this commit: b6458d9d40c2c4f2c54adaa9cd2f444f824f05c3.
> Release version v0.19.4

- api/entities.go
- api/entities_test.go
- cmd/reliably/slo/sync/cmd.go
Updated mechanism to use new entity server routes
Signed-off-by: mick-roper <mick@theropers.co.uk>
> reordered the args

- api/entities.go
- cmd/reliably/slo/report/cmd.go
> objres newpath

- api/entities.go
- api/entities_test.go
- cmd/reliably/slo/sync/cmd.go
* updated the path builder to point to the new routes
* added some tests for common failure conditions
> Update sync command

- CHANGELOG.md
- core/workflows/github.go
> Uses new GitHub action for scan command in GitHub workflow template

- cmd/reliably/root.go
- go.mod
- go.sum
- utils/uuid.go
- utils/uuid_test.go
> Improve check overridden org with env var - make a single call to API depending on UUID vs slug/name

- CHANGELOG.md
- cmd/reliably/root.go
> use user's default org when missing in config & env var - fixes #362

- CHANGELOG.md
This PR was created in response to a manual trigger by @dmartin35 of the release workflow here: https://github.com/reliablyhq/cli/actions/runs/993105619.
I've updated the changelog in this commit: bd84d80cf74fcd016809e45c3441c735dc55bbed.
> Release version v0.20.0

- api/entities.go
- cmd/reliably/slo/related/cmd.go
- embedded/nodegraph/static/visualise.js
This PR fixes the path used to call the entity-server graph endpoint
- fix relatedto path
- cleanedup comments
Resolves #382
> Fix relatedto path for Graph visualisation

- CHANGELOG.md
- cmd/reliably/worklow.go
- core/workflows/circleci.go
- core/workflows/github.go
- core/workflows/gitlab.go
> Add RELIABLY_ORG to workflow templates

- CHANGELOG.md
This PR was created in response to a manual trigger by @dmartin35 of the release workflow here: https://github.com/reliablyhq/cli/actions/runs/993621806.
I've updated the changelog in this commit: dbc04b2df5ea1105a6dff846893565bb0aaf2bfc.
> Release version v0.20.1

- api/client.go
- cmd/reliably/root.go
- cmd/reliably/slo/related/cmd.go
Adds `adds X-Reliably` headers to API calls from the CLI
> Add x-reliably-cmd headers

- CHANGELOG.md
- config/vars.go
> Update entity server host when reliably host env var is defined

- CHANGELOG.md
- api/entities.go
- api/entities_test.go
> do not lowercase org name when constructing url slug for entity server

- CHANGELOG.md
This PR was created in response to a manual trigger by @dmartin35 of the release workflow here: https://github.com/reliablyhq/cli/actions/runs/1015489926.
I've updated the changelog in this commit: 9ad62ee3cd74ee20cccbfae7b04c9c86c6e0dd2b.
> Release version v0.20.2

- core/report/map_report.go
Signed-off-by: Xavier <xaah@users.noreply.github.com>
> adding microseconds

- CHANGELOG.md
This PR was created in response to a manual trigger by @xaah of the release workflow here: https://github.com/reliablyhq/cli/actions/runs/1023185496.
I've updated the changelog in this commit: 4930a28d2059bf3680db651fa4b990181fedfd7a.
> Release version v0.20.3

- CHANGELOG.md
- core/report/map_report.go
- core/report/map_report_test.go
- added time format support and tests
- manifest message to debug log
> time parse tests

- CHANGELOG.md
- api/client.go
- cmd/reliably/root.go
- trace request body
- added trace log to previous REST client
> verbosity add

- CHANGELOG.md
- config/file.go
> Creates config folder before writing file; fixes #350

- CHANGELOG.md
This PR was created in response to a manual trigger by @dmartin35 of the release workflow here: https://github.com/reliablyhq/cli/actions/runs/1037924404.
I've updated the changelog in this commit: 41fd2cd61ce3028020ba9e93d1d3a0f89739af6f.
> Release version v0.20.4

- CHANGELOG.md
This PR was created in response to a manual trigger by @dmartin35 of the release workflow here: https://github.com/reliablyhq/cli/actions/runs/1044790707.
I've updated the changelog in this commit: d1981aca88b03f8ce9991cbc484b89342fa7dc2c.
> Release version v0.21.0

- core/metrics/datadog/metrics.go
Closes #409
Signed-off-by: Sylvain Hellegouarch <sh@defuze.org>
> Log DataDog query errors
